apiVersion: v1
kind: Secret
metadata:
  name: subees-secret
  namespace: subees
type: Opaque
stringData:
  db-url: jdbc:mariadb://mariadb-service:3306/subscription_db
  db-username: beyond
  db-password: beyond
  db-root-password: root
  jwt-secret: subees1234subees1234subees1234subees1234
